version: '3.8'

services:
  retool:
    image: tryretool/backend:latest
    container_name: retool
    ports:
      - "3000:3000"
    environment:
      # License (use TRIAL for free self-hosted, or get key from retool.com)
      LICENSE_KEY: "TRIAL"

      # Base domain (required for security)
      BASE_DOMAIN: "localhost:3000"

      # Retool database (stores Retool's own data - apps, users, etc)
      POSTGRES_DB: retool_db
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_SSL_ENABLED: "false"

      # JWT secret for sessions
      JWT_SECRET: "your-random-jwt-secret-change-this"
      ENCRYPTION_KEY: "your-random-encryption-key-change-this"

      # Force HTTPS off for local development
      FORCE_HTTPS: "false"

      # Node environment
      NODE_ENV: production

    volumes:
      - retool_data:/data

    # Add extra_hosts to access host machine's Postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped

volumes:
  retool_data:
    driver: local
