[build]
builder = "nixpacks"
buildCommand = "playwright install chromium --with-deps"

[deploy]
startCommand = "streamlit run src/admin/app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[environmentVariables]]
name = "DATABASE_URL"
description = "PostgreSQL connection string from Supabase"

[[environmentVariables]]
name = "OPENAI_API_KEY"
description = "OpenAI API key for agents"

[[environmentVariables]]
name = "NEYNAR_API_KEY"
description = "Neynar API key for Farcaster integration"

[[environmentVariables]]
name = "PERPLEXITY_API_KEY"
description = "Perplexity API key for LLM integration"

# Playwright configuration for Railway/containerized environments
[[environmentVariables]]
name = "PLAYWRIGHT_BROWSERS_PATH"
description = "Playwright browser cache path (set to /tmp/playwright)"

[[environmentVariables]]
name = "PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD"
description = "Skip browser download on pip install (set to 0 or omit)"

# Railway environment hints
[[environmentVariables]]
name = "PYTHONUNBUFFERED"
description = "Force Python stdout/stderr to be unbuffered (set to 1)"
